
#define TARGET_SHORT_ALIGNMENT 2
#define TARGET_INT_ALIGNMENT 4
#define TARGET_LLONG_ALIGNMENT 8
#define TARGET_I386 1

#define CONFIG_SOFTMMU 1
#define CONFIG_I386_DIS 1

#ifdef TARGET_X86_64
#define TARGET_LONG_ALIGNMENT 8
#define TARGET_PHYS_ADDR_BITS 64
#define TARGET_ARCH "x86-64"
#else
#define TARGET_LONG_ALIGNMENT 4
#define TARGET_PHYS_ADDR_BITS 32
#define TARGET_ARCH "i386"
#endif
#define TARGET_INSN_START_EXTRA_WORDS 1
